blog_affiche:
  path:     /affiche
  defaults: { _controller: BlogBundle:Comment:affiche }

blog_ajout:
  path:     /ajout
  defaults: { _controller: BlogBundle:Comment:ajout }

blog_delete:
  path:     /delete/{id}
  defaults: { _controller: BlogBundle:Comment:supprimer }

blog_edit:
  path:     /edit/{id}
  defaults: { _controller: BlogBundle:Comment:edit }